# Generated by Django 2.2.3 on 2019-10-17 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarmapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='timetable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=120, verbose_name='Username')),
                ('day_name', models.CharField(max_length=120, verbose_name='Username')),
                ('audio', models.CharField(max_length=120, verbose_name='Username')),
            ],
        ),
    ]
