# Generated by Django 2.2.3 on 2019-10-17 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alarmapp', '0002_timetable'),
    ]

    operations = [
        migrations.DeleteModel(
            name='timetable',
        ),
    ]
