# Generated by Django 2.2.3 on 2019-10-17 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarmapp', '0003_delete_timetable'),
    ]

    operations = [
        migrations.CreateModel(
            name='timetable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=120, verbose_name='Username')),
                ('day_name', models.CharField(max_length=120, verbose_name='day_name')),
                ('eight_to_nine', models.CharField(max_length=120, verbose_name='8 to 9')),
                ('nine_to_ten', models.CharField(max_length=120, verbose_name='9 to 10')),
                ('ten_to_eleven', models.CharField(max_length=120, verbose_name='10 to 11')),
                ('eleven_to_twelve', models.CharField(max_length=120, verbose_name='11 to 12')),
                ('twelve_to_one', models.CharField(max_length=120, verbose_name='12 to 1')),
                ('two_to_three', models.CharField(max_length=120, verbose_name='2 to 3')),
                ('three_to_four', models.CharField(max_length=120, verbose_name='3 to 4')),
                ('four_to_five', models.CharField(max_length=120, verbose_name='4 to 5')),
            ],
        ),
    ]
